version: '3'
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data

  elastic:
    image: elasticsearch:7.17.5
    environment:
      ES_JAVA_OPTS: "-Xms200m -Xmx200m"
      discovery.type: single-node

  redis:
    container_name: redis
    image: redis
    volumes:
      - ../data/redis:/data
    restart: always

  etl_genres_pipeline:
      build: 
        context: etl/
        dockerfile: genres.Dockerfile
      depends_on:
        - postgres
        - elastic
      env_file:
        - .env

  etl_persons_pipeline:
      build: 
        context: etl/
        dockerfile: persons.Dockerfile
      depends_on:
        - postgres
        - elastic
      env_file:
        - .env

  etl_filmwork_pipeline:
      build: 
        context: etl/
        dockerfile: film_works.Dockerfile
      depends_on:
        - postgres
        - elastic
      env_file:
        - .env

  api_service:
      build: 
        context: fastapi-solution/
        dockerfile: Dockerfile
      depends_on:
        - redis
        - elastic
      env_file:
        - .env
      restart: always

  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - api_service

volumes:
  esdata: